name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Run Buf API Linter and Check for Breaking Changes
        run: make local

  trigger-codegen:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Golang
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: zeromberto/giesskanne-apis-go
          event-type: codegen
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "repository": "${{ github.repository }}", "actor": "${{ github.actor }}"}'
